Selldim/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.views.static import serve

from Selldim.accounts import urls as accounts_urls
from Selldim.common import urls as common_urls
from Selldim.products import urls as product_urls
from Selldim.chat import urls as chat_urls
from Selldim.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(accounts_urls)),
    path('', include(common_urls)),
    path('product/', include(product_urls)),
    path('chat/', include(chat_urls)),


    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += \
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),\
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),


handler403 = "Selldim.common.views.error_403"
handler404 = "Selldim.common.views.error_404"
handler500 = "Selldim.common.views.error_500"

Selldim/products/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

CATEGORY_CHOICES = [
    ('electronics', 'Electronics'),
    ('hobby', 'Hobby'),
    ('sport', 'Sport'),
    ('animals', 'Animals'),
    ('vacantions', 'Vacantions'),
    ('vehicles', 'Vehicles'),
    ('clothes', "Clothes"),
    ('tools', 'Tools'),
    ('real estate', 'Real Estate'),
    ('other', 'Other'),
]


class Products(models.Model):
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    product_name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True, max_length=1000)
    price = models.FloatField(null=True, max_length=10)
    image = models.ImageField(null=True, upload_to='product_images')
    category = models.CharField(null=True, max_length=50, choices=CATEGORY_CHOICES)

    slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return f"{self.product_name} by {self.creator}"

    def save(self, *args, **kwargs):
        super(Products, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.category + '-' + self.product_name + '-' + str(self.id))
            self.save()





Selldim/common/forms.py
from django import forms


class ProductSearchForm(forms.Form):
    product_name = forms.CharField(
        max_length=50,
        required=False,
    )

Selldim/products/forms.py
from django import forms
from django.forms import ModelForm, TextInput, NumberInput, Select
from Selldim.products.models import Products


class ProductForm(ModelForm):

    class Meta:
        model = Products

        category = forms.ChoiceField(required=True)
        image = forms.ImageField(required=False)

        fields = ['product_name', 'category', 'image', 'description', 'price']

        widgets = {
            'product_name': TextInput(
                attrs={
                    'class': 'product--name',
                    'placeholder': 'Example: Apple Iphone 14pro 256gb',
                }),

            'image': forms.FileInput(
                attrs={
                    'class': 'product--image',
                    'multiple': 'False',
                    'onchange': 'readURL(this);'
                }),


            'description': forms.Textarea(
                attrs={
                    'class': 'product--description',
                    'onkeyup': "count();",
                    'placeholder': 'Write something that you think will convince someone to buy your product'
                }),

            'category': Select(attrs={
                'class': 'product--category',
                }),

            'price': NumberInput(attrs={
                'class': 'product--price',
                'min': '0',
                })
        }


class EditProductForm(ProductForm):
    pass


class DeleteProductForm(ProductForm):
    pass

templates/messages_page.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Messages</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'chat_room_page.css' %}">
    {% endblock %}
</head>




<html>
  <body>
  {% block content %}

<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
<div class="col-md-6">
            <div class="card card-bordered">
              <div class="card-header">
                <h4 class="card-title"><strong>Chat</strong></h4>
                <a class="btn btn-xs btn-secondary" href="#" data-abc="true">Let's Chat App</a>
              </div>


          <div class="ps-container ps-theme-default ps-active-y" id="chat-content" style="overflow-y: scroll !important; height:400px !important;">
                {% for msg in messages %}
                  {% if msg.sender != request.user %}
                  <div class="media media-chat media-chat-reverse">
                  <img class="avatar" src="" alt="...">
                  <div class="media-body">
                    <p>{{ msg.message }} :{{ msg.sender }}</p>
                  </div>
                </div>

                {% else %}
                 <div class="media media-chat">
                  <img class="avatar" src="{{ current_user_image.url }}" alt="...">
                  <div class="media-body">
                    <p>{{ msg.sender }}: {{ msg.message }}</p>
                  </div>
                </div>
                {% endif %}
                {% endfor %}
          </div>

<div class="publisher bt-1 border-light">
    <img class="avatar avatar-xs" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
    <input id="input" class="input" type="text" placeholder="Write something">
    <input id="submit" type="button" value="Send Message">

</div>



{#      --------------------------------------#}

  

{#  <textarea id="chat-text" cols="80" rows="30"></textarea><br>#}
{#  <input id="input" type="text" size="80"><br>#}
{#  <input id="submit" type="button" value="Send Message">#}
{#      --------------------------------------#}

        {{ room_name|json_script:'room_name' }}
        {{ request.user.username|json_script:'user_username' }}

        <script>
            const roomName = JSON.parse(document.getElementById('room_name').textContent);
            const user_username = JSON.parse(document.getElementById('user_username').textContent);


            document.querySelector('#submit').onclick = function (e) {
                const messageInputDom = document.querySelector('#input');
                const message = messageInputDom.value;

                chatSocket.send(JSON.stringify({
                    'message': message,
                    'user_username': user_username,
                    'room_name': roomName,

                }))
                messageInputDom.value = '';

            };


            {#Creates a new socket#}
            const chatSocket = new WebSocket(
                'ws://' +
                window.location.host +
                '/ws/chat/' +
                roomName +
                '/'
            );

            {#chatSocket.addEventListener('error', (event) => {#}
            {#    console.log('WebSocket error: ', event);#}
            {#);#}

            chatSocket.onmessage = function (e) {
                const data = JSON.parse(e.data);
                const new_message =
                            '<div class="media media-chat">' +
                            '<img class="avatar" src="{{ current_user_image.url }}" alt="...">' +
                            '<div class="media-body">' +
                            '<p> {{request.user}}: ' + data.message + '</p>' +
                            '<p class="meta"><time datetime="2018">00:06</time></p>' +
                            '</div>'


                document.querySelector('#chat-content').innerHTML += new_message
            };
        </script>

  {% endblock %}


  </body>
</html>

templates/my_ads.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'my_ads_page.css' %}">
    {% endblock %}
</head>


<body>

{% block content %}

    <div class="main__ads__div">
        {% for add in user_active_ads %}

            <div class="ads__div">
                    <div class="ads__inner__div">
                        <a class="image--a--tag" href="{% url 'product details' add.slug %}"></a>
                        <img src="{{ add.image.url }}" alt="" width="216px" height="157px">
                    </div>

                    <div class="add__name__div">
                        {{ add.product_name }}
                    </div>

                    <div class="add__price__div">
                        {{ add.price|floatformat:2 }} BGN
                    </div>
            </div>

            <div class="add--button--div">
                <a class="my--ads--add--button" href="{% url 'product edit' add.pk %}">Edit</a>
                <a class="my--ads--add--button" href="{% url 'product delete' add.pk %}">Delete</a>

            </div>

            {% endfor %}

    </div>



{% endblock %}

</body>





</html>

templates/my_favourite_ads.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'my_ads_page.css' %}">
    {% endblock %}
</head>



<body>
{% block content %}

    <div class="main__ads__div">
        {% for add in user_favourite_ads %}

            <div class="ads__div">
                    <div class="ads__inner__div">
                        <a class="image--a--tag" href="{% url 'product details' add.product.slug %}"></a>
                        <img src="{{ add.product.image.url }}" alt="" width="216px" height="157px">
                    </div>

                    <div class="add__name__div">
                        {{ add.product.product_name }}
                    </div>

                    <div class="add__price__div">
                        {{ add.product.price|floatformat:2 }} BGN
                    </div>

                    </div>

                {% if add.user == add.product.creator %}
                <div class="add--button--div">
                    <a class="my--ads--add--button" href="{% url 'product edit' add.product.pk %}">Edit</a>
                    <a class="my--ads--add--button" href="{% url 'product delete' add.product.pk %}">Delete</a>
                </div>
                {% endif %}

            </div>

        {% endfor %}
    </div>

{% endblock %}

</body>


</html>

templates/product_details.html
{% extends 'index.html' %}
{% load common_extras %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>Title</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'add_details_page.css' %}">
    {% endblock %}
</head>


<body>
    {% block content %}

    <div class="main--add--details--div">


        <div class="image--div--main">
            <div class="image--div">
                <img src="{{ product.image.url }}" width="580px" height="470px" alt="">
            </div>
        </div>

        <div class="name--price--description--wrap--div">

            <div class="name--price--description--div--main">
            <div class="name--price--div">
                {% if user_is_auth %}
                <span class="heart" style="padding-left: 95%">
                    <a href="{% url 'product like' product.id %}">
                        {% if product_liked_by_user %}
                            <svg style="color: red"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="24"
                                 height="24"
                                 fill="currentColor"
                                 class="bi bi-heart-fill"
                                 viewBox="0 0 16 16">
                                <!-- Coordinate path -->
                                <path fill-rule="evenodd"
                                      d="M8 1.314C12.438-3.248 23.534 4.735
                                                 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                      fill="red">
                                </path>
                            </svg>

                        {% else %}
                            <svg aria-label="Like"
                                 color="#262626"
                                 fill="#262626"
                                 height="24"
                                 role="img"
                                 viewBox="0 0 48 48"
                                 width="24">

                                <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                   11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                   41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                   11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                   1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                   1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                   1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                   0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                   1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                   1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                   7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                   48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                </path>
                            </svg>
                        {% endif %}
                    </a>
                </span>
                {% endif %}
                <h1 class="h1--name--tag">{{ product.product_name }}</h1>
                <h3 class="h3--price--tag">{{ product.price|floatformat:2 }} Bgn</h3>
            </div>

                <div class="description--div">
                    <div>
                        <h3 class="h3--description--tag">Description</h3>
                        {{ product.description }}
                    </div>
                    <div>

                        <a href="{% url 'room' product.creator|conc_str:user.username  %}">Send Message</a>
                    </div>
                </div>


        </div>
        </div>
    </div>

    {% endblock %}


</body>
</html>

templates/product_edit_page.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Sell</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'product_sell_page.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    {% endblock %}
</head>


<body>
{% block content %}


    {% if messages %}
        <ul style="display: flex; justify-content: center; align-items: center" class="messages">
        {% for message in messages %}
            <p class="flash--messages">{{ message }}</p>
        {% endfor %}
        </ul>
    {% endif %}


<div>
    <form class="product--sell--form" method="POST" action="{% url 'product edit' product.pk %}" enctype="multipart/form-data">
        {% csrf_token %}


        <div class="product--name--category--div">
            <h4 class="product--main--tag">What are you selling?</h4>
            <div class="label--product--name--div">
                <label  for="id_product_name" class="css-ha5hu8">Name</label>
                <div class="product--name--div">
                    {{ form.product_name }}
                </div>
            </div>


            <div class="label--product--category--div">
                <label  for="id_category">Categories</label>
                <div  class="product--category--div">
                    <label class="category--label" for="id_category">Choose a category</label>
                    {{ form.category }}
                </div>
            </div>


        </div>


        <div class="div--product--image">
            <h4 class="product--main--tag">Photos</h4>

            <div class="div--outer--image">
                <p>Here you can add an image of the product you are selling!</p>
                <div style="display: inline-flex">
                    <div class="div--image">
                        <p class="image--p--tag">Add an image</p>
                       {{ form.image }}
                    </div>
                    <div class="pre--upload--image--div" style="margin-left: 30px">
                        <svg  xmlns="http://www.w3.org/2000/svg" width="24" height="22" viewBox="0 0 33 32" data-testid="add-icon"><path fill="#406367" fill-rule="evenodd" d="M21.43 4l1.325 4h5.67l1.325 1.333v17.334L28.425 28H4.575L3.25 26.667V9.333L4.575 8h5.67l1.325-4h9.86zm-1.91 2.667h-6.04l-1.325 4H5.9v14.666h21.2V10.667h-6.255l-1.325-4zm-3.02 4c3.653 0 6.625 2.99 6.625 6.666S20.153 24 16.5 24s-6.625-2.99-6.625-6.667c0-3.676 2.972-6.666 6.625-6.666zm0 2.666c-2.192 0-3.975 1.794-3.975 4s1.783 4 3.975 4 3.975-1.794 3.975-4-1.783-4-3.975-4z"></path></svg>
                        <img src="{{ product.image.url }}" alt="" width="188px" height="141px">
                        <img style="position: absolute;" id="blah" src="#" alt="" />
                    </div>
                </div>

            </div>
            <div>

            </div>
        </div>




        <div class="div--product--description">
            <label for="id_description">Product description</label>
            <div class="div--description">
                {{ form.description }}
                <div class="description--word--counter--div">
                   <span id="total">Words: 0 / 1000 </span>
                </div>


            </div>

        </div>



        <div class="div--product--price">
            <label style="display: flex" for="id_price">Price</label>
            {{ form.price }}
            <p style="display: inline">BGN</p>
        </div>



        <div class="sale--page--input--button">
           <input class="input--button" type="submit" value="Apply Changes">
        </div>


    </form>
</div>


    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(188)
                        .height(141);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

    <script>
      function count()
    {
      var total=document.getElementById("id_description").value;
      total=total.replace(/\s/g, '');
      document.getElementById("total").innerHTML="Words: "+total.length+" / 1000";
    }
    </script>


{% endblock %}


</body>


</html>

templates/product_search_page.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'add_style.css' %}">
    <link rel="stylesheet" href="{% static 'search_bar.css' %}">

    <meta charset="UTF-8">
    <title>Title</title>
    {% endblock %}
</head>



<body>
{% block content %}
{# search bar#}
  <div id="cover">
  <form method="get" action="{% url 'product search' %}">
    {% csrf_token %}
    <div class="tb">
      <div class="td"><input name="search" type="text" placeholder="Search" required class="search--bar--input"></div>
      <div class="td" id="s-cover">
        <button type="submit">
          <div id="s-circle"></div>
          <span></span>
        </button>
      </div>
    </div>
  </form>
</div>
{# search bar end#}



<div class="card--div">

        <div class="header--div">
            <h1 class="header"></h1>
        </div>

        <ul class="card--ul">
            {% for product in products %}

            <li class="card--li">
                <div class="li--image--div">
                    <a class="image--a--tag" href="{% url 'product details' product.slug %}"></a>
                    <img src="{{ product.image.url }}" alt="" width="216px" height="156px">
                </div>

                <div class="li--name--div">
                    <p style="font-size: 16px; color: #6d44b8" class="product--name">{{ product.product_name }}</p>

                </div>

                <div class="li--price--div">
                    <p style="font-size: 16px; color: #6d44b8" class="product--price">Price: {{ product.price|floatformat:2 }} Bgn</p>
                </div>

            </li>

            {% endfor %}
        </ul>
    </div>


{% endblock %}
</body>



</html>

templates/profile_details.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>Sell</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'profile_details.css' %}">
        <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>

    {% endblock %}
</head>


<body>

{% block content %}

<div class="main">
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <p class="flash--messages">{{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}

				<form class="forms" method="POST" action="{% url 'profile details' user.username %}" enctype="multipart/form-data">
                    {% csrf_token %}

                <label style="margin: 20px" for="chk" aria-hidden="true">{{ user.username}}`s Profile</label>



                <h3 style="display: flex; justify-content: center; align-items: center">Profile Details</h3>
                    {{ form.username }}
                    {{ form.email }}
                    {{ form.first_name }}
                    {{ form.last_name }}
{#                  <p >In order to complete the changes please type your password and confirm it!</p>#}

                    <input class="input-button" type="submit" name="submit button" value="Edit Profile">


				</form>


                <form class="forms" method="POST" action="{% url 'profile details' user.username %}" enctype="multipart/form-data">
                    {% csrf_token %}


                      {% for field in form_picture %}


                    {% if user_picture %}
                          {{ field }}

                    <div class="profile--picture--div">
                        <img style="position: absolute; height: 200px;" id="blah" src="#" alt=""/>
                        <img  src="{{ user_picture.user_picture.url }}" alt="" width="200px" height="200px">
                    </div>

                    {% else %}
                        <div class="profile--picture--div">
                            {{ field }}
                            <img style="position: absolute; height: 200px;" id="blah" src="#" alt=""/>
                            <img  src="https://st3.depositphotos.com/4111759/13425/v/450/depositphotos_134255710-stock-illustration-avatar-vector-male-profile-gray.jpg" alt="" width="200px" height="200px">
                        </div>
                    {% endif %}

                    <input class="input-button" style="width: 200px; height: 30px; padding: 0px" type="submit" value="Save picture">
                      {% endfor %}
                </form>
			</div>


	</div>


    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

    <script>
        var form_fields = document.getElementsByTagName('input')
        form_fields[2].placeholder='Username'
        form_fields[3].placeholder='Email'
        form_fields[4].placeholder='First Name'
        form_fields[5].placeholder='Last Name'

    </script>

</body>
{% endblock %}

</html>

templates/sell_products_page.html
{% extends 'index.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Sell</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'product_sell_page.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    {% endblock %}
</head>


<body>
{% block content %}


    {% if messages %}
        <ul style="display: flex; justify-content: center; align-items: center" class="messages">
        {% for message in messages %}
            <p class="flash--messages">{{ message }}</p>
        {% endfor %}
        </ul>
    {% endif %}


<div>
    <form class="product--sell--form" method="POST" action="{% url 'sell' %}" enctype="multipart/form-data">
        {% csrf_token %}


        <div class="product--name--category--div">
            <h4 class="product--main--tag">What are you selling?</h4>
            <div class="label--product--name--div">
                <label  for="id_product_name" class="css-ha5hu8">Name</label>
                <div class="product--name--div">
                    {{ form.product_name }}
                </div>
            </div>


            <div class="label--product--category--div">
                <label  for="id_category">Categories</label>
                <div  class="product--category--div">
                    <label class="category--label" for="id_category">Choose a category</label>
                    {{ form.category }}
                </div>
            </div>


        </div>


        <div class="div--product--image">
            <h4 class="product--main--tag">Photos</h4>

            <div class="div--outer--image">
                <p>Here you can add an image of the product you are selling!</p>
                <div style="display: inline-flex">
                    <div class="div--image">
                        <p class="image--p--tag">Add an image</p>
                       {{ form.image }}
                    </div>
                    <div class="pre--upload--image--div" style="margin-left: 30px">
                        <svg  xmlns="http://www.w3.org/2000/svg" width="24" height="22" viewBox="0 0 33 32" data-testid="add-icon"><path fill="#406367" fill-rule="evenodd" d="M21.43 4l1.325 4h5.67l1.325 1.333v17.334L28.425 28H4.575L3.25 26.667V9.333L4.575 8h5.67l1.325-4h9.86zm-1.91 2.667h-6.04l-1.325 4H5.9v14.666h21.2V10.667h-6.255l-1.325-4zm-3.02 4c3.653 0 6.625 2.99 6.625 6.666S20.153 24 16.5 24s-6.625-2.99-6.625-6.667c0-3.676 2.972-6.666 6.625-6.666zm0 2.666c-2.192 0-3.975 1.794-3.975 4s1.783 4 3.975 4 3.975-1.794 3.975-4-1.783-4-3.975-4z"></path></svg>
                        <img style="position: absolute;" id="blah" src="#" alt="" />
                    </div>
                </div>

            </div>
            <div>

            </div>
        </div>


        <div class="div--product--description">
            <label for="id_description">Product description</label>
            <div class="div--description">
                {{ form.description }}
                <div class="description--word--counter--div">
                   <span id="total">Words: 0 / 1000 </span>
                </div>


            </div>

        </div>



        <div class="div--product--price">
            <label style="display: flex" for="id_price">Price</label>
            {{ form.price }}
            <p style="display: inline">BGN</p>
        </div>



        <div class="sale--page--input--button">
           <input class="input--button" type="submit" value="Sell Me">
        </div>


    </form>
</div>


    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(188)
                        .height(141);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

    <script>
      function count()
    {
      var total=document.getElementById("id_description").value;
      total=total.replace(/\s/g, '');
      document.getElementById("total").innerHTML="Words: "+total.length+" / 1000";
    }
    </script>



{% endblock %}


</body>


</html>